//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/liaomin/Documents/workspace/Android/DocPlusLogic/src/com/fq/http/async/HttpClient_IOS.java
//
//  Created by liaomin on 15-4-20.
//

#ifndef _ComFqHttpAsyncHttpClient_IOS_H_
#define _ComFqHttpAsyncHttpClient_IOS_H_

@class ComFqHttpAsyncParamsWrapper;
@protocol ComFqHttpPotocolHttpRequestPotocol;
@protocol FQHttpResponseHandle;

#import "JreEmulation.h"
#include "HttpClientPotocol.h"
#import "ICallback.h"

@interface ComFqHttpAsyncHttpClient_IOS : ComFqHttpPotocolHttpClientPotocol {
}

+(void)removHandle:(id)handel;

- (id<ComFqHttpPotocolHttpRequestPotocol>)sendPostRequestWithNSString:(NSString *)url
                                             withFQHttpResponseHandle:(id<FQHttpResponseHandle>)responseHandle;

- (id<ComFqHttpPotocolHttpRequestPotocol>)sendGetRequestWithNSString:(NSString *)url
                                            withFQHttpResponseHandle:(id<FQHttpResponseHandle>)responseHandle;

- (id<ComFqHttpPotocolHttpRequestPotocol>)sendPostRequestWithNSString:(NSString *)url
                                      withComFqHttpAsyncParamsWrapper:(ComFqHttpAsyncParamsWrapper *)params
                                             withFQHttpResponseHandle:(id<FQHttpResponseHandle>)responseHandle;

- (id<ComFqHttpPotocolHttpRequestPotocol>)sendGetRequestWithNSString:(NSString *)url
                                     withComFqHttpAsyncParamsWrapper:(ComFqHttpAsyncParamsWrapper *)params
                                            withFQHttpResponseHandle:(id<FQHttpResponseHandle>)responseHandle;

- (id<ComFqHttpPotocolHttpRequestPotocol>)sendPostRequestWithNSString:(NSString *)url
                                      withComFqHttpAsyncParamsWrapper:(ComFqHttpAsyncParamsWrapper *)params
                                             withFQHttpResponseHandle:(id<FQHttpResponseHandle>)responseHandle
                                                              withInt:(int)timeOut;

- (id<ComFqHttpPotocolHttpRequestPotocol>)sendGetRequestWithNSString:(NSString *)url
                                     withComFqHttpAsyncParamsWrapper:(ComFqHttpAsyncParamsWrapper *)params
                                            withFQHttpResponseHandle:(id<FQHttpResponseHandle>)responseHandle
                                                             withInt:(int)timeOut;

- (NSString *)encodeWithNSString:(NSString *)value;

- (NSString *)decodeWithNSString:(NSString *)value;

- (id)init;

@property (nonatomic,weak) id<ComFqLibCallbackICallback> sessionExpiredCallback;

@end

__attribute__((always_inline)) inline void ComFqHttpAsyncHttpClient_IOS_init() {}

#endif // _ComFqHttpAsyncHttpClient_IOS_H_
