//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/liaomin/Documents/workspace/Android/DocPlusLogic/src/com/fq/http/async/HttpClient_IOS.java
//
//  Created by liaomin on 15-4-20.
//

#line 1 "/Users/liaomin/Documents/workspace/Android/DocPlusLogic/src/com/fq/http/async/HttpClient_IOS.java"

#include "FQHttpResponseHandle.h"
#include "HttpClientPotocol.h"
#include "HttpClient_IOS.h"
#include "HttpRequestPotocol.h"
#include "IOSClass.h"
#include "ParamsWrapper.h"
#import "HttpResponseHandle.h"


static NSMutableArray* mHandles;

#line 7
@implementation ComFqHttpAsyncHttpClient_IOS


- (id)init {
    self = [super init];
    if(self){
        mHandles = [[NSMutableArray alloc] init];
        ComFqHttpPotocolHttpClientPotocol_mInstance_ = self;
    }
    return self;
}

+(void)removHandle:(id)handel
{
    if(mHandles)
    {
        [mHandles removeObject:handel];
    }
    
}

-(void)setOnSessionExpiredCallbackWithComFqLibCallbackICallback:(id<ComFqLibCallbackICallback>)callback
{
    _sessionExpiredCallback = callback;
}

- (id<ComFqLibCallbackICallback>)getOnSessionExpiredCallback
{
    return _sessionExpiredCallback;
}

#line 10
- (id<ComFqHttpPotocolHttpRequestPotocol>)sendPostRequestWithNSString:(NSString *)url
                                             withFQHttpResponseHandle:(id<FQHttpResponseHandle>)responseHandle {
  
#line 11
  return [self sendPostRequestWithNSString:url withComFqHttpAsyncParamsWrapper:nil withFQHttpResponseHandle:responseHandle];
}


#line 15
- (id<ComFqHttpPotocolHttpRequestPotocol>)sendGetRequestWithNSString:(NSString *)url
                                            withFQHttpResponseHandle:(id<FQHttpResponseHandle>)responseHandle {
  
#line 16
  return [self sendGetRequestWithNSString:url withComFqHttpAsyncParamsWrapper:nil withFQHttpResponseHandle:responseHandle];
}


#line 20
- (id<ComFqHttpPotocolHttpRequestPotocol>)sendPostRequestWithNSString:(NSString *)url
                                      withComFqHttpAsyncParamsWrapper:(ComFqHttpAsyncParamsWrapper *)params
                                             withFQHttpResponseHandle:(id<FQHttpResponseHandle>)responseHandle {
  
#line 21
  return [self sendPostRequestWithNSString:url withComFqHttpAsyncParamsWrapper:params withFQHttpResponseHandle:responseHandle withInt:ComFqHttpPotocolHttpClientPotocol_DEFAULT_TIME_OUT];
}


#line 25
- (id<ComFqHttpPotocolHttpRequestPotocol>)sendGetRequestWithNSString:(NSString *)url
                                     withComFqHttpAsyncParamsWrapper:(ComFqHttpAsyncParamsWrapper *)params
                                            withFQHttpResponseHandle:(id<FQHttpResponseHandle>)responseHandle {
  
#line 26
  return [self sendGetRequestWithNSString:url withComFqHttpAsyncParamsWrapper:params withFQHttpResponseHandle:responseHandle withInt:ComFqHttpPotocolHttpClientPotocol_DEFAULT_TIME_OUT];
}


#line 30
- (id<ComFqHttpPotocolHttpRequestPotocol>)sendPostRequestWithNSString:(NSString *)url
                                      withComFqHttpAsyncParamsWrapper:(ComFqHttpAsyncParamsWrapper *)params
                                             withFQHttpResponseHandle:(id<FQHttpResponseHandle>)responseHandle
                                                              withInt:(int)timeOut {
    HttpResponseHandle *hand = [[HttpResponseHandle alloc] initUrl:url WithParams:params andHandle:responseHandle isPost:YES timeout:timeOut];
    [mHandles addObject:hand];
#line 31
  return nil;
}


#line 35
- (id<ComFqHttpPotocolHttpRequestPotocol>)sendGetRequestWithNSString:(NSString *)url
                                     withComFqHttpAsyncParamsWrapper:(ComFqHttpAsyncParamsWrapper *)params
                                            withFQHttpResponseHandle:(id<FQHttpResponseHandle>)responseHandle
                                                             withInt:(int)timeOut {
    HttpResponseHandle *hand = [[HttpResponseHandle alloc] initUrl:url WithParams:params andHandle:responseHandle isPost:NO timeout:timeOut];
    [mHandles addObject:hand];
#line 36
  return nil;
}


#line 40
- (NSString *)encodeWithNSString:(NSString *)value {
  
#line 41
  return nil;
}


#line 45
- (NSString *)decodeWithNSString:(NSString *)value {
  return nil;
}


+ (J2ObjcClassInfo *)__metadata {
  static J2ObjcMethodInfo methods[] = {
    { "sendPostRequestWithNSString:withFQHttpResponseHandle:", "sendPostRequest", "Lcom.fq.http.potocol.HttpRequestPotocol;", 0x1, NULL },
    { "sendGetRequestWithNSString:withFQHttpResponseHandle:", "sendGetRequest", "Lcom.fq.http.potocol.HttpRequestPotocol;", 0x1, NULL },
    { "sendPostRequestWithNSString:withComFqHttpAsyncParamsWrapper:withFQHttpResponseHandle:", "sendPostRequest", "Lcom.fq.http.potocol.HttpRequestPotocol;", 0x1, NULL },
    { "sendGetRequestWithNSString:withComFqHttpAsyncParamsWrapper:withFQHttpResponseHandle:", "sendGetRequest", "Lcom.fq.http.potocol.HttpRequestPotocol;", 0x1, NULL },
    { "sendPostRequestWithNSString:withComFqHttpAsyncParamsWrapper:withFQHttpResponseHandle:withInt:", "sendPostRequest", "Lcom.fq.http.potocol.HttpRequestPotocol;", 0x1, NULL },
    { "sendGetRequestWithNSString:withComFqHttpAsyncParamsWrapper:withFQHttpResponseHandle:withInt:", "sendGetRequest", "Lcom.fq.http.potocol.HttpRequestPotocol;", 0x1, NULL },
    { "encodeWithNSString:", "encode", "Ljava.lang.String;", 0x1, NULL },
    { "decodeWithNSString:", "decode", "Ljava.lang.String;", 0x1, NULL },
    { "init", NULL, NULL, 0x1, NULL },
  };
  static J2ObjcClassInfo _ComFqHttpAsyncHttpClient_IOS = { "HttpClient_IOS", "com.fq.http.async", NULL, 0x1, 9, methods, 0, NULL, 0, NULL};
  return &_ComFqHttpAsyncHttpClient_IOS;
}

@end
