[
    {
        "date":"2015-5-6",
        "data":[
            {
                "type":1,//1:症状，2：诊断，3：检查，4：治疗（1:概览治疗，2：药物详细治疗），5：出院，6：入院
                "master":"主要症状",
                "slave":[
                    {
                        "name":"从属症状1",
                        "priority":2 //optional
                    },
                    {
                        "name":"从属症状2"
                    }
                ]
            },
            {
                "type":2,
                "diagnosis":[//诊断
                    {
                        "name":"炎症",
                    },
                    {
                        "name":"红斑狼疮"
                    }
                ]
            },
            {
                "type":3,
                "description":"xxx",//简单的描述
                "id":2001 //查看更多时需要
            },
            {
                "type":4,
                "subType":1,//概览治疗
                "treatment":[
                    {
                        "name":"抗感染",
                    },
                    {
                        "name":"护胃"
                    }
                ]
            },
        ]

    },
    {//药物详细治疗
        "date":"2015-5-6",
        "data":[
            {
                "type":4,
                "subType":2,//药物详细治疗
                "treatment":[
                    {
                        "name":"甲强龙",
                        "amount":"30g/天",
                        "start":"2015-5-1",
                        "end":"2015-5-4",
                    },
                    {
                        "name":"甲强龙2",
                        "amount":"30g/天",
                        "start":"2015-5-1",
                        "end":"2015-5-6",
                    }
                ]
            }
        ]
    },
    {//药物用量变化，新增药物需
        "date":"2015-5-4",
        "data":[
            {
                "type":4,
                "subType":2,
                "treatment":[
                    {
                        "name":"甲强龙",
                        "amount":"15g/天",
                        "start":"2015-5-4",
                        "end":"2015-5-6",
                    }
                ]
            }
        ]
    }
]