//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/liaomin/Documents/workspace/Android/DocPlusLogic/src/com/fq/http/async/Platform_IOS.java
//
//  Created by liaomin on 15-4-20.
//

#ifndef _ComFqHttpAsyncPlatform_IOS_H_
#define _ComFqHttpAsyncPlatform_IOS_H_

#import "JreEmulation.h"
#include "Platform.h"
#import "Reachability.h"

@interface ComFqHttpAsyncPlatform_IOS : ComFqLibPlatformPlatform {
    Reachability* reach;
}

- (id)init;

- (void)initNetWorkLibrary OBJC_METHOD_FAMILY_NONE;

- (void)initDes3Utils OBJC_METHOD_FAMILY_NONE;

- (void)initHMACSHA1 OBJC_METHOD_FAMILY_NONE;

- (void)scanFileWithNSString:(NSString *)path;

- (void)scanFileWithNSString:(NSString *)oldPath
                withNSString:(NSString *)newPath;

- (IOSByteArray *)getRecord3DesKey;

- (int)getTargetPlatform;

- (NSString *)SHA1WithNSString:(NSString *)text;

- (BOOL)setWithNSString:(NSString *)key
           withNSString:(NSString *)value;

- (NSString *)getWithNSString:(NSString *)key;

- (void)clearUser;

@end

__attribute__((always_inline)) inline void ComFqHttpAsyncPlatform_IOS_init() {}

#endif // _ComFqHttpAsyncPlatform_IOS_H_
